export const catalog = {
  classes: {
    class11: {
      label: "Class 11",
      subjects: [
        { key: "bio", label: "Biology" },
        { key: "cs", label: "Computer Science" },
        { key: "physics", label: "Physics" },
        { key: "maths", label: "Mathematics" },
        { key: "commerce", label: "Commerce" },
        { key: "humanities", label: "Humanities" },
      ],
    },
    class12: {
      label: "Class 12",
      subjects: [
        { key: "bio", label: "Biology" },
        { key: "cs", label: "Computer Science" },
        { key: "physics", label: "Physics" },
        { key: "chemistry", label: "Chemistry" },
        { key: "maths", label: "Mathematics" },
        { key: "commerce", label: "Commerce" },
        { key: "humanities", label: "Humanities" },
      ],
    },
  },
  courses: {
    bscCs: {
      label: "BSc Computer Science",
      semesters: {
        sem1: { label: "Semester 1", subjects: [] },
        sem2: { label: "Semester 2", subjects: [] },
        sem3: { label: "Semester 3", subjects: [] },
        sem4: {
          label: "Semester 4",
          subjects: [
            { key: "mathematics", label: "Mathematics" },
            { key: "microprocessor", label: "Microprocessor" },
          ],
        },
        sem5: { label: "Semester 5", subjects: [] },
        sem6: { label: "Semester 6", subjects: [] },
      },
    },
    bca: {
      label: "BCA",
      semesters: {
        sem1: { label: "Semester 1", subjects: [] },
        sem2: { label: "Semester 2", subjects: [] },
        sem3: { label: "Semester 3", subjects: [] },
        sem4: { label: "Semester 4", subjects: [] },
        sem5: { label: "Semester 5", subjects: [] },
        sem6: { label: "Semester 6", subjects: [] },
      },
    },
    economics: {
      label: "Economics",
      semesters: {
        sem1: { label: "Semester 1", subjects: [] },
        sem2: { label: "Semester 2", subjects: [] },
        sem3: { label: "Semester 3", subjects: [] },
        sem4: { label: "Semester 4", subjects: [] },
        sem5: { label: "Semester 5", subjects: [] },
        sem6: { label: "Semester 6", subjects: [] },
      },
    },
  },
};

export const defaultSeedNotes = [
  {
    title: "Plus Two Maths - Chapters 7 (eduport)",
    url: "/pdfs/MicroBit - Plus Two Maths - Chapters 7 (1).pdf",
    type: "pdf",
    scope: "class",
    classKey: "class12",
    subjectKey: "maths",
  },
  {
    title: "Plus Two Maths - Chapters 1,2,3,4,5,6,8 (eduport)",
    url: "/pdfs/MicroBit - Plus Two Maths - Chapter 1,2,3,4,5,6 & 8 (1).pdf",
    type: "pdf",
    scope: "class",
    classKey: "class12",
    subjectKey: "maths",
  },
  {
    title: "Chemistry Full Chapters Notes (eduport)",
    url: "/pdfs/MicroBit_Plus_Two_Chemistry_Full_Chapters_Notes_1,2,3,4,5,6,7,8.pdf",
    type: "pdf",
    scope: "class",
    classKey: "class12",
    subjectKey: "chemistry",
  },
  {
    title: "Named Reactions with Equation",
    url: "/pdfs/6. NAMED REACTIONS  WITH EQUATION.pdf",
    type: "pdf",
    scope: "class",
    classKey: "class12",
    subjectKey: "chemistry",
  },
  {
    title: "Amal Miss Notes",
    url: "/pdfs/Amal Miss.pdf",
    type: "pdf",
    scope: "course",
    courseKey: "bscCs",
    semesterKey: "sem4",
    subjectKey: "mathematics",
  },
  {
    title: "Infas Sir Notes",
    url: "/pdfs/Infas Sir.pdf",
    type: "pdf",
    scope: "course",
    courseKey: "bscCs",
    semesterKey: "sem4",
    subjectKey: "mathematics",
  },
  {
    title: "Sameeh Notes",
    url: "/pdfs/Sameeh’s 1.pdf",
    type: "pdf",
    scope: "course",
    courseKey: "bscCs",
    semesterKey: "sem4",
    subjectKey: "mathematics",
  },
  {
    title: "Microprocessor Notes",
    url: "/pdfs/Microprocessor micro sem 3.pdf",
    type: "pdf",
    scope: "course",
    courseKey: "bscCs",
    semesterKey: "sem4",
    subjectKey: "microprocessor",
  },
  {
    title: "Microprocessor 2021 QP",
    url: "/pdfs/mp april 2021.pdf",
    type: "pdf",
    scope: "course",
    courseKey: "bscCs",
    semesterKey: "sem4",
    subjectKey: "microprocessor",
  },
  {
    title: "Microprocessor 2022 QP",
    url: "/pdfs/mP 2022.pdf",
    type: "pdf",
    scope: "course",
    courseKey: "bscCs",
    semesterKey: "sem4",
    subjectKey: "microprocessor",
  },
  {
    title: "Microprocessor 2023 QP",
    url: "/pdfs/mp23.pdf",
    type: "pdf",
    scope: "course",
    courseKey: "bscCs",
    semesterKey: "sem4",
    subjectKey: "microprocessor",
  },
];
